#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Apr 18 12:56:04 MSK 2026
colorSpace=DISPLAY_P3
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=8
shaderPack=Body-Camera-Shader-V1.4.1.zip
enableShaders=true
