
[general]
	#Eables The printing of the Compass
	enableCompass = true
	#Widhth of the Compass
	#Range: 0 ~ 256
	compassWidth = 250
	#Sets Compass height from the top of the screen
	#Range: 0 ~ 256
	compassFromTop = 3
	#Sets Compass Opacity
	#Range: 0 ~ 100
	compassOpacity = 15

